export const possible = {
  Industry: [
    "Apparel & Accessories",
    "Electronics & Gadgets",
    "Home & Garden",
    "Health & Beauty",
    "Sports, Fitness & Outdoors",
    "Toys, Kids & Baby Products",
    "Automotive & Industrial",
    "Food, Beverage & Grocery",
    "Books, Media & Entertainment",
    "Pet Supplies & Animal Care",
    "Arts, Crafts & Hobbies",
    "Jewelry & Watches",
    "Office Supplies & Stationery",
    "Gifts, Occasions & Party Supplies",
    "Software & Digital Products",
    "Travel Accessories & Luggage",
    "Musical Instruments & Equipment",
    "Collectibles & Memorabilia",
    "Beauty & Personal Care",
    "Miscellaneous & Specialty Items",
  ],
  "Brand Tone": [
    "Friendly",
    "Professional",
    "Casual",
    "Formal",
    "Playful",
    "Serious",
    "Innovative",
    "Traditional",
    "Modern",
    "Vintage",
    "Luxurious",
    "Affordable",
    "Energetic",
    "Calm",
    "Bold",
    "Subtle",
    "Trustworthy",
    "Edgy",
    "Sophisticated",
    "Down-to-Earth",
    "Minimalist",
    "Extravagant",
    "Organic",
    "Technological",
    "Artistic",
    "Educational",
    "Inspirational",
    "Humorous",
    "Warm",
    "Cool",
    "Inclusive",
    "Exclusive",
    "Nostalgic",
    "Futuristic",
    "Empowering",
    "Sustainable",
    "Whimsical",
    "Practical",
    "Family-Oriented",
    "Cutting-Edge",
  ],
}
