export const possible = {
  Industry: [
    'Apparel',
    'Footwear',
    'Jewelry',
    'Luxury',
    'Sustainable',
    'Athleisure',
    'Tech Wear',
    'Custom',
    'Streetwear',
    'Activewear',
    'Other',
  ],
  Aesthetics: [
    'Minimal',
    'Modern',
    'Vintage',
    'Bold',
    'Subtle',
    'Eco',
    'Genderless',
    'Androgynous',
    'Statement',
    'Classic',
    'Retro',
    'Street',
    'Luxury',
    'Affordable',
    'Artisan',
    'Avant-Garde',
    'High-Perf',
  ],
  'Business Size': ['Small', 'Mid', 'Large'],
  'Business Type': [
    'T-shirt',
    'Sweater',
    'Hoodie',
    'Jacket',
    'Pants',
    'Shorts',
    'Skirt',
    'Dress',
    'Blazer',
    'Coat',
    'Accessory',
    'Footwear',
    'Jewelry',
    'Handbag',
    'Tech',
    'Custom',
    'Other',
  ],
  'Target Audience': ['Men', 'Women', 'Unisex', 'Kids', 'Luxury', 'Eco', 'Athletes', 'Techies'],
  'Geographic Focus': ['Local', 'Regional', 'National', 'International', 'Global', 'Localized'],
  'Brand Story': [
    'Minimal',
    'Modern',
    'Vintage',
    'Bold',
    'Subtle',
    'Eco',
    'Inclusive',
    'Neutral',
    'Statement',
    'Classic',
    'Retro',
    'Street',
    'High-End',
    'Luxury',
    'Handmade',
    'Tech-Driven',
    'Sized',
    'Heritage',
    'Avant-Garde',
  ],
}
