export const possible = {
  Industry: ['Apparel', 'Accessories', 'Footwear', 'Jewelry', 'Other'],
  Aesthetics: [
    'Minimal',
    'Modern',
    'Vintage',
    'Bold',
    'Subtle',
    'Eco-friendly',
    'Gendered',
    'Unisex',
    'Statement',
    'Classic',
    'Retro',
    'Streetwear',
    'High-end',
    'Luxury',
    'Affordable',
  ],
  'Business Size': ['Small', 'Medium', 'Large'],
  'Business Type': [
    'T-shirt',
    'Sweater',
    'Hoodie',
    'Jacket',
    'Pants',
    'Shorts',
    'Skirt',
    'Dress',
    'Blazer',
    'Coat',
    'Accessory',
    'Footwear',
    'Jewelry',
    'Other',
  ],
  'Target Audience': ['Men', 'Women', 'Unisex', 'Children'],
  'Geographic Focus': ['Local', 'Mostly Local', 'National', 'International', 'Global'],
  'Brand Story': [
    'Minimal',
    'Modern',
    'Vintage',
    'Bold',
    'Subtle',
    'Eco-friendly',
    'Gendered',
    'Unisex',
    'Statement',
    'Classic',
    'Modern',
    'Retro',
    'Streetwear',
    'High-end',
    'Luxury',
    'Affordable',
    'Eco-friendly',
    'Gendered',
    'Unisex',
    'Statement',
    'Classic',
    'Modern',
    'Retro',
    'Streetwear',
    'High-end',
    'Luxury',
    'Affordable',
  ],
}
